version: "3"

services:
  server:
    build: ./apache
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d:ro
